language: php
env:
  global:
    - XDEBUG_MODE=coverage
    - CODECOV_TOKEN=69603dfb-4614-4c46-981d-fea1bf942272

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
