language: php
env:
  global:
    - XDEBUG_MODE=coverage

php:
  - 7.4

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit
