language: php
dist: bionic
os: linux

env:
  global:
    - XDEBUG_MODE=coverage
    - CODECOV_TOKEN=69603dfb-4614-4c46-981d-fea1bf942272

jobs:
  include:
    - php: 7.3
      env: SYMFONY_VERSION='^3.4'
    - php: 7.3
      env: SYMFONY_VERSION='^4.0'
    - php: 7.3
      env: SYMFONY_VERSION='^5.0'

    - php: 7.4
      env: SYMFONY_VERSION='^3.4'
    - php: 7.4
      env: SYMFONY_VERSION='^4.0'
    - php: 7.4
      env: SYMFONY_VERSION='^5.0'

    - php: 8.0
      env: SYMFONY_VERSION='^5.4'
    - php: 8.0
      env: SYMFONY_VERSION='^5.0'
    - php: 8.0
      env: SYMFONY_VERSION='^5.0'
  allow_failures:
    - php: nightly
      env: SYMFONY_VERSION='^3.4'
    - php: nightly
      env: SYMFONY_VERSION='^4.0'
    - php: nightly
      env: SYMFONY_VERSION='^5.0'

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev --no-progress
  - composer config extra.symfony.require "$SYMFONY_VERSION"

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
